---
language: node_js
node_js:
  - "6"

env:
  global:
    - PATH="~/.linuxbrew/bin:~/.linuxbrew/sbin:/usr/local/bin:$PATH"
  matrix:
    - LISP=clozure-cl
    # TODO: get CMUCL to find OpenSSL
    # - LISP=cmucl
    - LISP=ecl
    - LISP=sbcl

matrix:
  allow_failures:
    # until their linuxbrew formulae are fixed
    env: LISP=ecl
    env: LISP=clozure-cl

services:
  - redis-server

before_install:
  - sudo mkdir -p /usr/local
  - sudo chown -R "$USER:" /usr/local
  - HOME=/home/linuxbrew
  - sudo mkdir $HOME
  - sudo chown "$USER:" $HOME
  - LINUXBREW=$HOME/.linuxbrew
  - mkdir $LINUXBREW
  - curl -L https://github.com/Linuxbrew/brew/tarball/master | tar xz -m --strip 1 -C $LINUXBREW
  - export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH"
  - brew update || brew update
  - brew install openssl libyaml "$LISP"
  - if [[ "$LISP" == "clozure-cl" ]]; then export LISP=ccl64; fi
  - make bin/blockparty

before_script:
  - mv config/oauth.yml.template config/oauth.yml

script:
  - make tests
  - if [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      bin/serve;
      sleep 8;
      curl -IL localhost:3000;
      cat log/access.log;
      npm test;
    fi

notifications:
  email: false
