---
language: common-lisp

os:
  - osx
  - linux

env:
  global:
    - PATH=$HOME/.roswell/bin:$PATH
  matrix:
    - LISP=ccl
    # TODO: get CMUCL to find OpenSSL
    # - LISP=cmucl
    - LISP=ecl
    - LISP=sbcl

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get -qq update;
      sudo apt-get install -y redis-server libssl-dev;
      sudo service redis-server start;
    fi
  - bash "$TRAVIS_BUILD_DIR/scripts/ci.sh"

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      export LISP=ros;
    elif [ "$LISP" = "ccl" ]; then
      export LISP=ccl64;
    elif [ "$LISP" = "cmucl" ]; then
      export LISP=lisp;
    fi

script:
  - make ql
  - make dist-install
  - make tests

notifications:
  email: false
