---
language: node_js
node_js:
  - "6"

env:
  global:
    - PATH="/usr/local/qi/bin:~/.linuxbrew/bin:~/.linuxbrew/sbin:/usr/local/bin:$PATH"
  matrix:
    - LISP=sbcl
    # TODO: get CMUCL to find OpenSSL
    # - LISP=cmucl
    # Commented out until their linuxbrew formulae are fixed
    # - LISP=ecl
    # - LISP=clozure-cl

services:
  - redis-server

before_install:
  - sudo mkdir -p /usr/local
  - sudo chown -R "$USER:" /usr/local
  - HOME=/home/linuxbrew
  - sudo mkdir $HOME
  - sudo chown "$USER:" $HOME
  - LINUXBREW=$HOME/.linuxbrew
  - mkdir $LINUXBREW
  - curl -L https://github.com/Linuxbrew/brew/tarball/master | tar xz -m --strip 1 -C $LINUXBREW
  - export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH"
  - brew update || brew update
  - brew install openssl libyaml "$LISP"
  - if [[ "$LISP" == "clozure-cl" ]]; then export LISP=ccl64; fi
  - git clone --depth=1 --branch=install-deps https://github.com/dunn/qi.git /usr/local/qi

before_script:
  - mv config/oauth.yml.template config/oauth.yml
  - qi --install-deps blockparty.asd
  - cp -r /usr/local/qi/dependencies/* ./.dependencies/packages/

script:
  - make tests
  - if [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      bin/serve;
      sleep 8;
      curl -IL localhost:3000;
      cat log/access.log;
      npm test;
    fi

notifications:
  email: false
