---
language: node_js
node_js:
  - "6"

env:
  global:
    - PATH=$HOME/.roswell/bin:/usr/local/bin:$PATH
  matrix:
    - LISP=ccl
    # TODO: get CMUCL to find OpenSSL
    # - LISP=cmucl
    - LISP=ecl
    - LISP=sbcl

services:
  - redis-server

before_install:
  - npm install
  - sudo apt-get -qq update;
  - sudo apt-get install -y libssl-dev;
  - bash "$TRAVIS_BUILD_DIR/scripts/ci.sh"

before_script:
  - mv config/oauth.yml.template config/oauth.yml
  - make blockparty
  - export LISP=ros;

script:
  - make tests
  - ./blockparty
  - curl -IL localhost:3000
  - cat log/access.log
  - npm test

notifications:
  email: false
