---
language: common-lisp
sudo: false

os:
  - linux
  - osx

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      PATH=~/.roswell/bin:$PATH;
      curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh;
      ros install $LISP;
    else
      brew update;
      if [ "$LISP" = "ccl" ]; then
        brew install clozure-cl;
        export LISP=ccl64;
      else
        brew install $LISP;
      fi
    fi

script:
  - make ql
  - make dist-install
  - make test
